### ISSUE TITLE
All/ any other 2018 lab assignments ready?

### ISSUE THREAD

**Issue by arthur-e** [OscarFHC/EAS538_2018#11]
Hi @mehajain13,

Given the difficulty we had with the Week 2 lab and the persistent challenge of targeting the right difficulty level for students, I was wondering if any other labs for this semester (Week 3, Week 4, ...) were currently ready for Oscar and I to take a look at?

In my personal opinion, most students are requiring a lot more help than anticipated on the lab assignments. Some of that will improve as their familiarity with R improves, but I want to take a deep dive in the lab assignments each week before running them so I can try and identify any potential trouble spots.

And, of course, bugs in datasets and typos can happen any time, so the more time and eyes we have on the labs the better!

Thanks!
Arthur

**Comment by mehajain13** [comment]
Hey @arthur-e 

I agree - all of us looking at the labs more in advance will help ensure problems like this week don't happen again and will help you both prep for the labs in advance. No other labs are ready yet, but I'll plan to get you the next two labs by Sunday night. Also, I asked one of the undergrads working in my lab to spend 2 hours every Monday doing the labs on her own and sending me notes about any problems she runs into - that should give us another fresh set of eyes to find potential problems in advance.

Thanks!
m
