### ISSUE TITLE
Week 3 lab answer key?

### ISSUE THREAD

**Issue by arthur-e** [OscarFHC/EAS538_2018#19]
Hi @OscarFHC,

If you have already started work on creating the answer key for the Week 3 lab (Assignment 2), please let me know. Otherwise, I will start on it.

Thanks,
Arthur

**Comment by OscarFHC** [comment]
I've not yet done so. I plan to do so tomorrow morning. You can start it
Thanks,

**Comment by OscarFHC** [comment]
@arthur-e I just graded the assignment and found that students still interpret the confidence interval as follow. You might want to take that into account when making the answer key. 
"there is 95% chance that the true mean of the population lies in the interval of 64.99307 and 65.07210."
"95% of means from random samples will be between these two values."
"a 95% probability that any given confidence interval from a random sample will contain the true population mean"

**Comment by arthur-e** [comment]
Thanks! I just created it. Look for the pull request.
