### ISSUE TITLE
New chisquare/ANOVA lab

### ISSUE THREAD

**Issue by mehajain13** [OscarFHC/EAS538_2018#22]
Hey @arthur-e & @OscarFHC - I've added the updated ANOVA lab to week 5. I named this one 'new.Rmd' at the end because I ended up changing the file a lot from Oscar's original to better align with what students learned in lab this week. I wrote this lab sort of quickly, so please go through and make sure I didn't make any mistakes! I'll also go through the lab again tomorrow afternoon when I'm freed up from meetings.

Thanks!!
m

**Comment by arthur-e** [comment]
Looks great! I love that the Bechdel test makes an appearance.

**Comment by OscarFHC** [comment]
No objection from here as well.
