### ISSUE TITLE
Answer key for assignment 3 (t-test)

### ISSUE THREAD

**Issue by OscarFHC** [OscarFHC/EAS538_2018#23]
Hi, 

I just pushed the answer key for assignment 3. Please review it especially for the language in explaining why there is a trivial problem using t-test in this non-normally distributed data.
Thank you.
OSCAR

**Comment by arthur-e** [comment]
Looks great! I made some minor changes; will push soon.

Also, if you have 5-10 minutes today to stop by 2004 Dana, I would appreciate your opinion on some supplemental material I'm preparing for the beginning of lab today (starts at 3:00 PM).

**Comment by OscarFHC** [comment]
I just found many typo and editorial error...I'll push it again.

**Comment by arthur-e** [comment]
Okay, I'll be careful, so we don't have a complicated merge...

**Comment by OscarFHC** [comment]
Thanks and sorry for my mistakes. I just pushed it.

**Comment by OscarFHC** [comment]
Btw, I'll come to DANA around 1:30 and will stop by your office for sure.

**Comment by arthur-e** [comment]
Thanks! I merged my changes with yours and put the knit HTML answer key up on Canvas.
