### ISSUE TITLE
Week 9 lab posted

### ISSUE THREAD

**Issue by mehajain13** [OscarFHC/EAS538_2018#31]
Hey @arthur-e and @OscarFHC 

I've uploaded the lab for this week to the week 9 folder. Since I created a different lab from last year, I didn't overwrite the original .Rmd and instead marked mine with _MJ.Rmd at the end.

Let me know if you have any questions and/or suggestions and apologies for the short turn around time! 
m

**Comment by arthur-e** [comment]
@OscarFHC I have checked out this lab and am making changes; will push by 12:00 PM noon today.

**Comment by OscarFHC** [comment]
OK, I'm looking at it now and do not have concerns about the content. I'll take a look again later then.

**Comment by arthur-e** [comment]
Just submitted a PR, #32, with only minor formatting changes.

**Comment by OscarFHC** [comment]
I'm good with this version. Publishing to canvas now.
