### ISSUE TITLE
GLM assignment answer key

### ISSUE THREAD

**Issue by OscarFHC** [OscarFHC/EAS538_2018#38]
@mehajain13  and @arthur-e 
I've created the answer key for the GLM assignment. 
I noticed there might be a small error in the lab when interpreting the meaning of coefficients . We had...

>So we can think of the odds = 1.46 = 1.46/1, which means the odds of a household moving is 1.46 and the odds of a household staying is 1. How much greater is 1.46 than 1 in percentage terms? That’s 1.46 - 1 = 0.46* 100% = 46%. So another way to interpret your result is for every ppm increase in arsenic, a household is 46% more likely to move.    

It is correct that the odds increases 1.46, but the probability should only increase to 51.8% (`(exp(-0.30553 + 0.37914)/(1+exp(-0.30553 + 0.37914)))`). It is not " 46% more likely to move". 

I added the correct formula in the answer key. Please correct me if I'm wrong.

**Comment by arthur-e** [comment]
If the odds increase by a factor of 1.46 then the odds increase by 46%, I think that is all that was meant in the lab. As the odds are the factor by which a family is more likely to move than not (with an odds of 1.0 meaning "equal chance of moving or not moving") I think that the following are equivalent:

- The odds of a household moving are 46% higher
- A households is 46% more likely to move

I think you've correctly calculated the probability of a success (i.e., of a household moving), but the text in the lab is about the increase in the *odds* of moving.

**Comment by arthur-e** [comment]
I think the key words are "factor" and "more" (or "less"). So, when we say "46% *more* likely to move" we mean that the odds have increased by 46%, *not* that the probability of a move is 46% or gets 46% added to whatever it was before.

**Comment by OscarFHC** [comment]
I see. I did not make such argument in the answer key as I'm not sure how to phrase it correctly. I always said the odds increase/decrease by X% or the probability becomes X%.
Anyway, please double check the language in the answer key I created then. Thanks.
