### ISSUE TITLE
Lab operations, instructions for students

### ISSUE THREAD

**Issue by arthur-e** [OscarFHC/EAS538_2018#9]
Hi @mehajain13 @OscarFHC 

I have some unresolved questions about running the lab, what to tell students about their assignments, etc. Some of this came up as Oscar and I were putting the finishing touches on the Week 2 lab Thursday morning and he and I made some executive decisions...

1. We were unsure whether or not to give students the lab as an *.Rmd file or as a compiled HTML file. Oscar and I had made the decision to share the HTML file so that students are encouraged to type-in the examples.
2. We also chose to hide all the output in the compiled HTML file, again, so students are actually typing the R commands and getting the output for themselves.
3. Anything I'm forgetting? I made an RMarkdown template which structures what I think their submitted assignments look like (on Canvas, in Lab > Week2 > EAS538_Assignment1_template.Rmd). Please check that out and see my comments below.

Also, @OscarFHC, I want to confirm that the following are our mutually agreed-upon, "official" instructions to the students about turning in the assignments. I made these checkboxes so just check a box if you agree!

- [x] Students can turn in their assignment as one of the following files (only): HTML, PDF, or Microsoft Word (*.doc, *.docx)/ OpenOffice/ LibreOffice rich text document;
- [x] While using RMarkdown is encouraged, the raw *.Rmd cannot be accepted for their assignment;
- [x] Submitted assignments should only contain the answers to the exercises, which should be clearly marked with headers, e.g., "Exercise 1," "Exercise 2," etc.
- [x] Except where stated otherwise, students should clearly show their R input commands, the relevant R output (using `head()` if the output is too large), and answering any questions with complete sentences.

Thanks!

**Comment by arthur-e** [comment]
Also...

4. Students were a bit confused about all the material in the lab that they weren't expected to turn in. I think it just requires better framing. Obviously, the bulk of the material in the "Week2_EDA_In_class.html" file is for their benefit--they should complete all the examples so they improve their understanding of R. In practice, however, after I show them RMarkdown, they're confused about what they should be putting in their RMarkdown document. (I've personally also felt that RMarkdown is a bit clunky in interactive mode.) So, I think I'm going to encourage my students to open a *.R script for working on the lab and to start a *.Rmd file **just** for the assigned exercises. Appreciate any other suggestions you have.

**Comment by mehajain13** [comment]
Hey Arthur - I agree with all of your points. Students should only turn in the exercises to you & Oscar (though we expect that they will finish the full lab). I'll be sure to try to make the next lab more clear regarding what they are supposed to turn in. I think the idea to work in an .R script and just save the .Rmd for the assignments is also a good idea. Thanks to you both for all of your suggestions and improvements!

**Comment by OscarFHC** [comment]
Thanks, Arthur. I'll make the assignment policy more clear in class and post what you have here to the assignment description section on canvas. 
As to use *.R script in the lab and use *.Rmd for their assignment, I'm more leaning toward having students decide for themselves. I just think that more exposure to RMarkdown might implicitly encourage them to trun in *.html, which can be a benefit for us. 
However, I agree with you that it will be confusing what to put in in the RMarkdown, so how about I move all the exercises to to bottom of the document? That way I can have policy descriptions before the __Exercise__ section and students won't be distracted by the exercise while going through the materials. If you agree with that, I can do so for the following weeks.

**Comment by mehajain13** [comment]
Hi @OscarFHC & @arthur-e  - I would prefer if we left the Exercises where they currently are in the document and not move them to the end since they logically flow in terms of the datasets students are working with, new code they learned, etc. I think we can just make it clear at the top of the document that students should turn in the exercises only. Thanks!

**Comment by OscarFHC** [comment]
Sure, I'll make things more clear in the beginning. Thanks.
